<?xml version="1.0" encoding="utf-8"?>

<!--  $Id: passsubscriber.wsdl,v 1.5 2004/02/04 16:01:58 dgardner Exp $  -->

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
             xmlns:xs="http://www.w3.org/2001/XMLSchema" 
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
             xmlns:xsd1="http://peoc3t.us.army.mil/PASS" 
             xmlns:tns="http://peoc3t.us.army.mil/PASS/wsdl" 
             xmlns:ports="http://peoc3t.us.army.mil/PASS/ports" 
             targetNamespace="http://peoc3t.us.army.mil/PASS/wsdl">

    <import namespace="http://peoc3t.us.army.mil/PASS/ports"  location="passports.wsdl" />

    <documentation>
       This document defines the PASS Subscriber.
    </documentation>

    <service name="PASSSubscriber">
        <port binding="ports:PASSSubscriberPortBinding" name="PASSSubscriber">
            <soap:address location="http://someplace.com/"/>
        </port>
    </service>

</definitions>
