/* soapPASSPortBindingProxy.h
   Generated by gSOAP 2.7.17 from ../pass.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapPASSPortBindingProxy_H
#define soapPASSPortBindingProxy_H
#include "soapH.h"

class SOAP_CMAC PASSPortBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'PASSPortBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	PASSPortBindingProxy();
	/// Constructor with copy of another engine state
	PASSPortBindingProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	PASSPortBindingProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	PASSPortBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~PASSPortBindingProxy();
	/// Initializer used by constructors
	virtual	void PASSPortBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'subscribe' (returns error code or SOAP_OK)
	virtual	int subscribe(_pass__subscribe *pass__subscribe, pass__status *pass__status_);

	/// Web service operation 'retract_item' (returns error code or SOAP_OK)
	virtual	int retract_USCOREitem(_pass__retract_USCOREitem *pass__retract_USCOREitem, pass__status *pass__status_);

	/// Web service operation 'retract_topic' (returns error code or SOAP_OK)
	virtual	int retract_USCOREtopic(_pass__retract_USCOREtopic *pass__retract_USCOREtopic, pass__status *pass__status_);

	/// Web service operation 'unsubscribe' (returns error code or SOAP_OK)
	virtual	int unsubscribe(_pass__unsubscribe *pass__unsubscribe, pass__status *pass__status_);

	/// Web service operation 'publish' (returns error code or SOAP_OK)
	virtual	int publish(_pass__publish *pass__publish, pass__status *pass__status_);

	/// Web service operation 'create_topic' (returns error code or SOAP_OK)
	virtual	int create_USCOREtopic(_pass__create_USCOREtopic *pass__create_USCOREtopic, pass__status *pass__status_);

	/// Web service operation 'sync' (returns error code or SOAP_OK)
	virtual	int sync(_pass__sync *pass__sync, _pass__sync_USCOREresponse *pass__sync_USCOREresponse);
};
#endif
