/* soapPASSSubscriberPortBindingProxy.cpp
   Generated by gSOAP 2.7.17 from ../pass.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapPASSSubscriberPortBindingProxy.h"

PASSSubscriberPortBindingProxy::PASSSubscriberPortBindingProxy()
{	PASSSubscriberPortBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PASSSubscriberPortBindingProxy::PASSSubscriberPortBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

PASSSubscriberPortBindingProxy::PASSSubscriberPortBindingProxy(soap_mode iomode)
{	PASSSubscriberPortBindingProxy_init(iomode, iomode);
}

PASSSubscriberPortBindingProxy::PASSSubscriberPortBindingProxy(soap_mode imode, soap_mode omode)
{	PASSSubscriberPortBindingProxy_init(imode, omode);
}

void PASSSubscriberPortBindingProxy::PASSSubscriberPortBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"xlink", "http://www.w3.org/1999/xlink", NULL, NULL},
	{"ns1", "http://peoc3t.us.army.mil/PASS/ports/PASSPortBinding", NULL, NULL},
	{"pass", "http://peoc3t.us.army.mil/PASS", NULL, NULL},
	{"ns2", "http://peoc3t.us.army.mil/PASS/ports/PASSSubscriberPortBinding", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	this->namespaces = namespaces;
}

PASSSubscriberPortBindingProxy::~PASSSubscriberPortBindingProxy()
{ }

void PASSSubscriberPortBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void PASSSubscriberPortBindingProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *PASSSubscriberPortBindingProxy::soap_fault()
{	return this->fault;
}

const char *PASSSubscriberPortBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *PASSSubscriberPortBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int PASSSubscriberPortBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

void PASSSubscriberPortBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void PASSSubscriberPortBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *PASSSubscriberPortBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int PASSSubscriberPortBindingProxy::publish(_pass__publish *pass__publish, pass__status *pass__status_)
{	struct soap *soap = this;
	struct __ns2__publish soap_tmp___ns2__publish;
	const char *soap_action = NULL;
	soap->encodingStyle = NULL;
	soap_tmp___ns2__publish.pass__publish = pass__publish;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__publish(soap, &soap_tmp___ns2__publish);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__publish(soap, &soap_tmp___ns2__publish, "-ns2:publish", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__publish(soap, &soap_tmp___ns2__publish, "-ns2:publish", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!pass__status_)
		return soap_closesock(soap);
	pass__status_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	pass__status_->soap_get(soap, "pass:status", "pass:status");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PASSSubscriberPortBindingProxy::retract_USCOREitem(_pass__retract_USCOREitem *pass__retract_USCOREitem, pass__status *pass__status_)
{	struct soap *soap = this;
	struct __ns2__retract_USCOREitem soap_tmp___ns2__retract_USCOREitem;
	const char *soap_action = NULL;
	soap->encodingStyle = NULL;
	soap_tmp___ns2__retract_USCOREitem.pass__retract_USCOREitem = pass__retract_USCOREitem;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__retract_USCOREitem(soap, &soap_tmp___ns2__retract_USCOREitem);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__retract_USCOREitem(soap, &soap_tmp___ns2__retract_USCOREitem, "-ns2:retract_item", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__retract_USCOREitem(soap, &soap_tmp___ns2__retract_USCOREitem, "-ns2:retract_item", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!pass__status_)
		return soap_closesock(soap);
	pass__status_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	pass__status_->soap_get(soap, "pass:status", "pass:status");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PASSSubscriberPortBindingProxy::retract_USCOREtopic(_pass__retract_USCOREtopic *pass__retract_USCOREtopic, pass__status *pass__status_)
{	struct soap *soap = this;
	struct __ns2__retract_USCOREtopic soap_tmp___ns2__retract_USCOREtopic;
	const char *soap_action = NULL;
	soap->encodingStyle = NULL;
	soap_tmp___ns2__retract_USCOREtopic.pass__retract_USCOREtopic = pass__retract_USCOREtopic;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__retract_USCOREtopic(soap, &soap_tmp___ns2__retract_USCOREtopic);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__retract_USCOREtopic(soap, &soap_tmp___ns2__retract_USCOREtopic, "-ns2:retract_topic", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__retract_USCOREtopic(soap, &soap_tmp___ns2__retract_USCOREtopic, "-ns2:retract_topic", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!pass__status_)
		return soap_closesock(soap);
	pass__status_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	pass__status_->soap_get(soap, "pass:status", "pass:status");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PASSSubscriberPortBindingProxy::unsubscribe(_pass__unsubscribe *pass__unsubscribe, pass__status *pass__status_)
{	struct soap *soap = this;
	struct __ns2__unsubscribe soap_tmp___ns2__unsubscribe;
	const char *soap_action = NULL;
	soap->encodingStyle = NULL;
	soap_tmp___ns2__unsubscribe.pass__unsubscribe = pass__unsubscribe;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__unsubscribe(soap, &soap_tmp___ns2__unsubscribe);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__unsubscribe(soap, &soap_tmp___ns2__unsubscribe, "-ns2:unsubscribe", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__unsubscribe(soap, &soap_tmp___ns2__unsubscribe, "-ns2:unsubscribe", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!pass__status_)
		return soap_closesock(soap);
	pass__status_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	pass__status_->soap_get(soap, "pass:status", "pass:status");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
