/* soapPASSPortBindingService.cpp
   Generated by gSOAP 2.7.17 from ../pass.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapPASSPortBindingService.h"

PASSPortBindingService::PASSPortBindingService()
{	PASSPortBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PASSPortBindingService::PASSPortBindingService(const struct soap &_soap) :soap(_soap)
{ }

PASSPortBindingService::PASSPortBindingService(soap_mode iomode)
{	PASSPortBindingService_init(iomode, iomode);
}

PASSPortBindingService::PASSPortBindingService(soap_mode imode, soap_mode omode)
{	PASSPortBindingService_init(imode, omode);
}

PASSPortBindingService::~PASSPortBindingService()
{ }

void PASSPortBindingService::PASSPortBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"xlink", "http://www.w3.org/1999/xlink", NULL, NULL},
	{"ns1", "http://peoc3t.us.army.mil/PASS/ports/PASSPortBinding", NULL, NULL},
	{"pass", "http://peoc3t.us.army.mil/PASS", NULL, NULL},
	{"ns2", "http://peoc3t.us.army.mil/PASS/ports/PASSSubscriberPortBinding", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	this->namespaces = namespaces;
};

void PASSPortBindingService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

PASSPortBindingService *PASSPortBindingService::copy()
{	PASSPortBindingService *dup = SOAP_NEW_COPY(PASSPortBindingService(*(struct soap*)this));
	return dup;
}

int PASSPortBindingService::soap_close_socket()
{	return soap_closesock(this);
}

int PASSPortBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int PASSPortBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int PASSPortBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int PASSPortBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void PASSPortBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void PASSPortBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *PASSPortBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void PASSPortBindingService::soap_noheader()
{	header = NULL;
}

int PASSPortBindingService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()))
				return this->error;
			(void)serve();
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET PASSPortBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET PASSPortBindingService::accept()
{	return soap_accept(this);
}

int PASSPortBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{	soap_begin(this);
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			this->error = SOAP_EOF;
			return soap_send_fault(this);
		}
#endif

		soap_begin(this);

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_recv(this))
		{	if (this->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(this);
#else 
				return soap_send_fault(this);
#endif
			}
			soap_closesock(this);

			continue;
		}

		if (soap_envelope_begin_in(this)
		 || soap_recv_header(this)
		 || soap_body_begin_in(this)
		 || dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___ns1__subscribe(PASSPortBindingService*);
static int serve___ns1__retract_USCOREitem(PASSPortBindingService*);
static int serve___ns1__retract_USCOREtopic(PASSPortBindingService*);
static int serve___ns1__unsubscribe(PASSPortBindingService*);
static int serve___ns1__publish(PASSPortBindingService*);
static int serve___ns1__create_USCOREtopic(PASSPortBindingService*);
static int serve___ns1__sync(PASSPortBindingService*);

int PASSPortBindingService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "pass:subscribe"))
		return serve___ns1__subscribe(this);
	if (!soap_match_tag(this, this->tag, "pass:retract_item"))
		return serve___ns1__retract_USCOREitem(this);
	if (!soap_match_tag(this, this->tag, "pass:retract_topic"))
		return serve___ns1__retract_USCOREtopic(this);
	if (!soap_match_tag(this, this->tag, "pass:unsubscribe"))
		return serve___ns1__unsubscribe(this);
	if (!soap_match_tag(this, this->tag, "pass:publish"))
		return serve___ns1__publish(this);
	if (!soap_match_tag(this, this->tag, "pass:create_topic"))
		return serve___ns1__create_USCOREtopic(this);
	if (!soap_match_tag(this, this->tag, "pass:sync"))
		return serve___ns1__sync(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve___ns1__subscribe(PASSPortBindingService *soap)
{	struct __ns1__subscribe soap_tmp___ns1__subscribe;
	pass__status pass__status_;
	pass__status_.soap_default(soap);
	soap_default___ns1__subscribe(soap, &soap_tmp___ns1__subscribe);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__subscribe(soap, &soap_tmp___ns1__subscribe, "-ns1:subscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->subscribe(soap_tmp___ns1__subscribe.pass__subscribe, &pass__status_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__status_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__status_.soap_put(soap, "pass:status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__status_.soap_put(soap, "pass:status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__retract_USCOREitem(PASSPortBindingService *soap)
{	struct __ns1__retract_USCOREitem soap_tmp___ns1__retract_USCOREitem;
	pass__status pass__status_;
	pass__status_.soap_default(soap);
	soap_default___ns1__retract_USCOREitem(soap, &soap_tmp___ns1__retract_USCOREitem);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__retract_USCOREitem(soap, &soap_tmp___ns1__retract_USCOREitem, "-ns1:retract_item", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->retract_USCOREitem(soap_tmp___ns1__retract_USCOREitem.pass__retract_USCOREitem, &pass__status_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__status_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__status_.soap_put(soap, "pass:status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__status_.soap_put(soap, "pass:status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__retract_USCOREtopic(PASSPortBindingService *soap)
{	struct __ns1__retract_USCOREtopic soap_tmp___ns1__retract_USCOREtopic;
	pass__status pass__status_;
	pass__status_.soap_default(soap);
	soap_default___ns1__retract_USCOREtopic(soap, &soap_tmp___ns1__retract_USCOREtopic);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__retract_USCOREtopic(soap, &soap_tmp___ns1__retract_USCOREtopic, "-ns1:retract_topic", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->retract_USCOREtopic(soap_tmp___ns1__retract_USCOREtopic.pass__retract_USCOREtopic, &pass__status_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__status_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__status_.soap_put(soap, "pass:status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__status_.soap_put(soap, "pass:status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__unsubscribe(PASSPortBindingService *soap)
{	struct __ns1__unsubscribe soap_tmp___ns1__unsubscribe;
	pass__status pass__status_;
	pass__status_.soap_default(soap);
	soap_default___ns1__unsubscribe(soap, &soap_tmp___ns1__unsubscribe);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__unsubscribe(soap, &soap_tmp___ns1__unsubscribe, "-ns1:unsubscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->unsubscribe(soap_tmp___ns1__unsubscribe.pass__unsubscribe, &pass__status_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__status_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__status_.soap_put(soap, "pass:status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__status_.soap_put(soap, "pass:status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__publish(PASSPortBindingService *soap)
{	struct __ns1__publish soap_tmp___ns1__publish;
	pass__status pass__status_;
	pass__status_.soap_default(soap);
	soap_default___ns1__publish(soap, &soap_tmp___ns1__publish);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__publish(soap, &soap_tmp___ns1__publish, "-ns1:publish", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->publish(soap_tmp___ns1__publish.pass__publish, &pass__status_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__status_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__status_.soap_put(soap, "pass:status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__status_.soap_put(soap, "pass:status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__create_USCOREtopic(PASSPortBindingService *soap)
{	struct __ns1__create_USCOREtopic soap_tmp___ns1__create_USCOREtopic;
	pass__status pass__status_;
	pass__status_.soap_default(soap);
	soap_default___ns1__create_USCOREtopic(soap, &soap_tmp___ns1__create_USCOREtopic);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__create_USCOREtopic(soap, &soap_tmp___ns1__create_USCOREtopic, "-ns1:create_topic", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->create_USCOREtopic(soap_tmp___ns1__create_USCOREtopic.pass__create_USCOREtopic, &pass__status_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__status_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__status_.soap_put(soap, "pass:status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__status_.soap_put(soap, "pass:status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns1__sync(PASSPortBindingService *soap)
{	struct __ns1__sync soap_tmp___ns1__sync;
	_pass__sync_USCOREresponse pass__sync_USCOREresponse;
	pass__sync_USCOREresponse.soap_default(soap);
	soap_default___ns1__sync(soap, &soap_tmp___ns1__sync);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__sync(soap, &soap_tmp___ns1__sync, "-ns1:sync", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->sync(soap_tmp___ns1__sync.pass__sync, &pass__sync_USCOREresponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	pass__sync_USCOREresponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || pass__sync_USCOREresponse.soap_put(soap, "pass:sync_response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || pass__sync_USCOREresponse.soap_put(soap, "pass:sync_response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
