
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl LibAmmoSerialization
// ------------------------------
#ifndef LIBAMMOSERIALIZATION_EXPORT_H
#define LIBAMMOSERIALIZATION_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (LIBAMMOSERIALIZATION_HAS_DLL)
#  define LIBAMMOSERIALIZATION_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && LIBAMMOSERIALIZATION_HAS_DLL */

#if !defined (LIBAMMOSERIALIZATION_HAS_DLL)
#  define LIBAMMOSERIALIZATION_HAS_DLL 1
#endif /* ! LIBAMMOSERIALIZATION_HAS_DLL */

#if defined (LIBAMMOSERIALIZATION_HAS_DLL) && (LIBAMMOSERIALIZATION_HAS_DLL == 1)
#  if defined (LIBAMMOSERIALIZATION_BUILD_DLL)
#    define LibAmmoSerialization_Export ACE_Proper_Export_Flag
#    define LIBAMMOSERIALIZATION_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define LIBAMMOSERIALIZATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* LIBAMMOSERIALIZATION_BUILD_DLL */
#    define LibAmmoSerialization_Export ACE_Proper_Import_Flag
#    define LIBAMMOSERIALIZATION_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define LIBAMMOSERIALIZATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* LIBAMMOSERIALIZATION_BUILD_DLL */
#else /* LIBAMMOSERIALIZATION_HAS_DLL == 1 */
#  define LibAmmoSerialization_Export
#  define LIBAMMOSERIALIZATION_SINGLETON_DECLARATION(T)
#  define LIBAMMOSERIALIZATION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* LIBAMMOSERIALIZATION_HAS_DLL == 1 */

// Set LIBAMMOSERIALIZATION_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (LIBAMMOSERIALIZATION_NTRACE)
#  if (ACE_NTRACE == 1)
#    define LIBAMMOSERIALIZATION_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define LIBAMMOSERIALIZATION_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !LIBAMMOSERIALIZATION_NTRACE */

#if (LIBAMMOSERIALIZATION_NTRACE == 1)
#  define LIBAMMOSERIALIZATION_TRACE(X)
#else /* (LIBAMMOSERIALIZATION_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define LIBAMMOSERIALIZATION_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (LIBAMMOSERIALIZATION_NTRACE == 1) */

#endif /* LIBAMMOSERIALIZATION_EXPORT_H */

// End of auto generated file.
