#!/bin/sh

set -e

USERNAME=ammo-gateway
GROUPNAME=ammo-gateway
HOMEDIR=/var/run/ammo-gateway

getent group $GROUPNAME >/dev/null || groupadd -r $GROUPNAME
getent passwd $SERNAME>/dev/null || \
    useradd -r -g $GROUPNAME-d $HOMEDIR-s /sbin/nologin \
    -c "AMMO Gateway User" $USERNAME

exit 0

