#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ammo-gateway" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d ammo-gateway stop || exit $?
        else
                /etc/init.d/ammo-gateway stop || exit $?
        fi
fi
# End automatically added section
